# Generated by Django 5.1.4 on 2025-02-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'AssetCategory',
            },
        ),
        migrations.CreateModel(
            name='AssetSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='AccetCategory.assetcategory')),
            ],
            options={
                'db_table': 'AssetSubCategory',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='AssetReg_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('asset_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('Company_Brand', models.CharField(max_length=500)),
                ('current_location', models.CharField(max_length=500)),
                ('room_no', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_working_life', models.IntegerField(blank=True, null=True)),
                ('expected_working_life', models.IntegerField(blank=True, null=True)),
                ('valuation_method', models.CharField(blank=True, max_length=250, null=True)),
                ('is_new_asset', models.BooleanField(default=True)),
                ('depreciation_method', models.CharField(blank=True, max_length=250, null=True)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('appreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_registrations', to='AccetCategory.assetcategory')),
                ('asset_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccetCategory.assetsubcategory')),
            ],
            options={
                'db_table': 'AssetReg_Data',
            },
        ),
        migrations.CreateModel(
            name='AssetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=50)),
                ('valuation_method', models.CharField(choices=[('none', 'None'), ('depreciated', 'Depreciated'), ('appreciation', 'Appreciation')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccetCategory.assetcategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccetCategory.assetsubcategory')),
            ],
            options={
                'db_table': 'AssetList',
            },
        ),
        migrations.CreateModel(
            name='AssetDocuments_Uplode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('file', models.BinaryField(editable=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssetDocuments_Uplode', to='AccetCategory.assetcategory')),
                ('asset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccetCategory.assetreg_data')),
                ('asset_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssetDocuments_Uplode', to='AccetCategory.assetsubcategory')),
            ],
            options={
                'db_table': 'AssetDocuments_Uplode',
            },
        ),
        migrations.CreateModel(
            name='Asset_ServiceProviderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('cost_effective', models.BooleanField(default=True)),
                ('service_quality', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='fair', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_response_time', models.CharField(default='1 day', max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('asset_categories', models.ManyToManyField(blank=True, to='AccetCategory.assetcategory')),
                ('subcategories', models.ManyToManyField(blank=True, to='AccetCategory.assetsubcategory')),
            ],
            options={
                'db_table': 'Asset_ServiceProviderManagement',
            },
        ),
        migrations.CreateModel(
            name='ChecklistMasterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChecklistMasterEntry', to='AccetCategory.assetcategory')),
                ('subcategories', models.ManyToManyField(related_name='ChecklistMasterEntry', to='AccetCategory.assetsubcategory')),
            ],
            options={
                'db_table': 'ChecklistMasterEntry',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('ranking', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='AccetCategory.assetcategory')),
                ('subcategories', models.ManyToManyField(related_name='suppliers', to='AccetCategory.assetsubcategory')),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.AddField(
            model_name='assetreg_data',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='AccetCategory.supplier'),
        ),
    ]
