# Generated by Django 5.1.4 on 2025-02-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccetCategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreg_data',
            name='asset_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccetCategory.assetsubcategory'),
        ),
    ]
